### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by Linux-Geezer** [half-duplex/hugo-arcana#1]
I started playing around with your theme tonight and received the following error message after running _hugo serve_:

`DEPRECATION WARNING on line 7 of .../themes/hugo-arcana/assets/sass/libs/_breakpoints.scss:
!global assignments won't be able to declare new variables in future versions.
Consider adding '$breakpoints: null' at the top level.`

**Comment by half-duplex** [comment]
Thanks for the nudge to figure this out!

**Comment by Linux-Geezer** [comment]
Thank you for the excellent theme, for the quick response, and the quick fix.
