### ISSUE TITLE
Can I use more than one yml-file in this template to load content from?

### ISSUE THREAD

**Issue by Kay-S** [half-duplex/hugo-arcana#13]
Hi there,

thank you for your work. I'm still new to this and your theme works great. I would like to have a second page on my website project that acts exactly like the homepage.yml. For example data\test.yml with content\test.md to control the menu position. How is that possible?

Best wishes

**Comment by half-duplex** [comment]
I moved the homepage layout into _default and added a param, so you can do this now.

Create `yoursite/content/index2.md`, containing e.g.
```md
---
title: Home2
layout: home
homepage_data: homepage2
menu: main
weight: 11
---
```
Configure it in yoursite/data/en/homepage2.yml, with contents like the other homepage.yml file.
