### ISSUE TITLE
Rendering HTML

### ISSUE THREAD

**Issue by EliasB-NU** [half-duplex/hugo-arcana#15]
Hi there,

Is it possible to render HTML written in a markdown file?
I tried putting in my HTML but it wasn´t rendered on the website.

**Comment by smolski** [comment]
Me too.

**Comment by mseankelly** [comment]
@TechnicGamerHD @smolski I know that you posted this some time ago, but perhaps the answer will be helpful to others.

Hugo uses Goldmark for markdown. According to the Hugo documentation:

> By default, Goldmark does not render raw HTML and potentially dangerous links.

You can, however, configure Goldmark to render raw HTML by setting Goldmark's `unsafe` configuration property to `true`. See more details on the [configuration-markup page](https://gohugo.io/getting-started/configuration-markup/) in the Hugo documentation.
