### ISSUE TITLE
Changing the palette

### ISSUE THREAD

**Issue by mseankelly** [half-duplex/hugo-arcana#16]
I'd like to change the palette located in `assets/sass/libs/_vars.scss`:

```
// Palette.
    $palette: (
        bg: #f7f7f7,
        fg: #474747,
        fg-bold: #4c4c4c,
        fg-light: #999,
        border: #e0e0e0,

        accent: (
            bg: #37c0fb,
            fg: #fff
        )
    );
```

How can I do that without editing Arcana in the submodule?

**Comment by half-duplex** [comment]
In `your_site/assets/sass/libs/_custom_vars.scss`,
```scss
$palette: map_merge($palette, (
    bg: #ff00ff,
    fg: #00ff00,
    [...]
));
```

If you specify anything within another map, say `accent`, it will replace the entire default `accent`, so you need to specify every member of `accent` or do another map_merge like this:
```scss
$palette: map_merge($palette, (
    accent: map_merge(map_get($palette, accent), (
        bg: #ff00ff
    ))
));
```

**Comment by sutux** [comment]
The custom file `your_site/assets/sass/libs/_custom_vars.scss` could also look for example like (if you want to replace the complete palette):

```
$palette: (
    bg: #2f2f2f,
    fg: #f7f7f7,
    fg-bold: #4c4c4c,
    fg-light: #999,
    border: #e0e0e0,
    second-color: #ffd959,

    accent: (
        bg: #66cbff,
        fg: #fff
    ),

    obscure: (
        bg: #1e1e1e,
        bg-bold: #1f1f1f,
        fg: #c0c0c0
    )
);
```
