### ISSUE TITLE
In mobile layout, the top title is not clickable

### ISSUE THREAD

**Issue by mathieugouin** [half-duplex/hugo-arcana#17]
In mobile view, I have tried to make the top title page clickable to go to the home page like the desktop version, but without luck.

You can refer to the attached screen shot.

I would be happy to provide a PR but I'm not sure where to start.  It seems that this part is done in Javascript instead of plain html/css.

Thanks !
![Screenshot_20240304-093507_Chrome](https://github.com/half-duplex/hugo-arcana/assets/11562302/ff713935-a281-4c6f-83ce-f78972125175)

**Comment by alichampi** [comment]
That part is generated in `assets/js/main.js` at lines 39-44:
```
        // Bar.
            $(
                '<div id="titleBar">' +
                    '<a href="#navPanel" class="toggle"></a>' +
                    '<span class="title">' + $('#logo').html() + '</span>' +
                '</div>'
            )

**Comment by mathieugouin** [comment]
@alichampi Thanks for the response.  I will try in that area.  Any idea why it was not clickable?  Any rationale I should be aware of?

**Comment by alichampi** [comment]
Only case I can come up with is that a fix like `window.location = '/';` would send you to the wrong page if your `BaseURL`  is something like `example.com/example` but that's only speculation from my part.

**Comment by alichampi** [comment]
@mathieugouin Hi, we actually wanted to have this on our website, so I took it upon myself to do it. It wasn't as easy as I thought but I think I managed to do it. For now, you can check it out on the [header-fix branch of my fork](https://github.com/alichampi/hugo-arcana/tree/header-fix). I'll make the proper pull request after #19 is merged, as I didn't organized my branches properly so there are duplicate changes.

**Comment by mathieugouin** [comment]
Thanks @alichampi I will have a look!

**Comment by mathieugouin** [comment]
Your website looks very nice by the way ;)

**Comment by alichampi** [comment]
@mathieugouin Oh, thank you! ❤️
I've had some time so I managed to make a new branch with only the necessary changes so I could be able to open the PR #20 now to save time.

**Comment by alichampi** [comment]
@mathieugouin Just a heads up: The change is made on the official repository!
Also, it has fixes for my original PR, so tomorrow I'll be deleting my fork.
