### ISSUE TITLE
Dynamic Copyright Year

### ISSUE THREAD

**Issue by Linux-Geezer** [half-duplex/hugo-arcana#2]
I like to include the year I started my blog and the current year as part of the copyright text; e.g. &copy; 2018 - 2022. I found a method to automatically adjust the current year, but it might be helpful for others to already have the functionality baked into the theme.

I can't find the thread on the Hugo forums that I used to change my customized version of your theme, but the following links use the same technique that I found in the Hugo forums thread:

https://stackoverflow.com/questions/60865779/how-can-i-update-the-copyright-information-in-hugo-theme

https://rynkowski.uk/hugo-dynamic-copyright-year/

**Comment by half-duplex** [comment]
Automatic year updates seem silly to me, since listing the year at all is of dubious legal utility, but it's easy enough to implement. Set `copyright = "© You {currentYear}"`.

**Comment by half-duplex** [comment]
Also, note that you can override most things in a theme by just copying e.g. `layouts/partials/footer/footer.html` to the same location in your site repo and making whatever changes you wish.
