### ISSUE TITLE
modification of color inside globalheader

### ISSUE THREAD

**Issue by shellchocolat** [half-duplex/hugo-arcana#4]
Hello, I would like to modify the color of the **globalheader** text.

I add a line inside the **custom.scss** file:
`    .gh_color {
        color: #FF6347; 
    }
`

Then,  inside the **globalheader.yml** :
`
title: "not colored / <div class='gh_color '>Colored</div>"
`

But clearly no html code is allowed here as no color modification happens.

Could you tell me the location of the code that I have to modify?

**Comment by half-duplex** [comment]
You can put something like this in `custom.scss` to change all of the text:
```css
#header>h1 {
    color: #FF6347;
}
```
Does that accomplish what you need, or do you need both colored and non-colored text there?
