### ISSUE TITLE
Discuss changes before submitting a PR?

### ISSUE THREAD

**Issue by pbklink** [half-duplex/hugo-arcana#6]
@half-duplex - I would like to make some (further) enhancements to this theme.  Would you like me to post an issue regarding changes before submitting a PR?

**Comment by half-duplex** [comment]
That's probably preferable, I wouldn't want you to spend time on something we'll end up wanting a different strategy for.

**Comment by pbklink** [comment]
Probably easier for both of us if I create a new separate upstream repository with a snapshot of this repository.

Thanks for your work in creating this and looking at the existing PR.
