### ISSUE TITLE
Multilingual Support

### ISSUE THREAD

**Issue by half-duplex** [half-duplex/hugo-arcana#7]
It would be great to have built-in multilingual support.

**Comment by ikks** [comment]
I would like to have multilingual support, I saw the PR but I didn't understand what needs to be done it to be merged, maybe I could help on this.

**Comment by half-duplex** [comment]
This is an issue, not a PR, so no code yet unfortunately. If you know how to implement it a PR would be very welcome.

**Comment by half-duplex** [comment]
The PR is just waiting on me to re-review. I'll bump it up my todo list.

**Comment by ikks** [comment]
Sorry, I explained very badly, thank you for all what you do. crossing fingers here so the PR can be incorporated https://github.com/half-duplex/hugo-arcana/pull/11

**Comment by half-duplex** [comment]
Implemented by #11
