### ISSUE TITLE
Customizing head.html

### ISSUE THREAD

**Issue by pinx** [half-duplex/hugo-arcana#9]
To add an icon, I wanted to add my own custom head html file.

The instruction in https://github.com/half-duplex/hugo-arcana/blob/main/layouts/partials/head/custom.html

are outdated, it seems. I had to put the file in `layouts\partials\head`

In case anyone wants to know how to add this icon:  
Put this in custom.html:  
`<link rel="shortcut icon" sizes="192x192" href="images/icon.png">`

**Comment by half-duplex** [comment]
Fixed, thank you for pointing this out!
